// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Next.js は .env.local を使う。Prisma CLI も同じファイルを読めるように設定
import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" }); // フォールバック

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
